<?php

/**
 * Implementation of hook_form_FORM_ID_alter().
 */

function info_api_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
  $form['site_information']['siteapikey'] = array(
    '#type' => 'textfield',
    '#title' => t('Site API Key'),
    '#description' => t('Input your API key here.'),
    '#default_value' => \Drupal::config('info_api.settings')->get('siteapikey') ? \Drupal::config('info_api.settings')->get('siteapikey') : 'No API Key yet',
  );
  $form['actions']['submit']['#value'] = t('Update Configuration');
  $form['#submit'][] = 'info_api_submit_handler';
}

/**
 * Submit handler for site configuration
 */
function info_api_submit_handler(&$form, Drupal\Core\Form\FormStateInterface $form_state) {
  $apikey = $form_state->getValue('siteapikey');
  $site_config = \Drupal::service('config.factory')->getEditable('info_api.settings');
  $site_config->set('siteapikey', $apikey)->save();
  if($site_config){
    drupal_set_message(t('Site API Key has been updated.'), 'status');
  }
}
